name: release-dotnet-tool
on:
  release:
    types: [released]

jobs:
  release:
    runs-on: windows-latest
    environment: release
    steps:
    - name: Download package from release and publish
      run: |
        $github = Get-Content '${{ github.event_path }}' | ConvertFrom-Json
        $asset = $github.release.assets | Where-Object -Property name -match '.nupkg$'

        dotnet nuget push $asset.name --api-key ${{ secrets.NUGET_API_KEY }} --source https://apiint.nugettest.org/v3/index.json
      shell: powershell
