name: release

on:
  workflow_dispatch:
  push:
    branches: [ release, main ]

jobs:
  create-dotnet-tool:
    name: Publish dotnet tool
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0 # Indicate full history so Nerdbank.GitVersioning works.

    - name: Setup .NET
      uses: actions/setup-dotnet@v3.0.2
      with:
        dotnet-version: 6.0.201

    - uses: dotnet/nbgv@master
      with:
        setCommonVars: true

    - name: Test version
      run: |
        echo $GitBuildVersionSimple

    # - name: Package tool
    #   run: |
    #     src/shared/DotnetTool/pack-tool.sh \
    #       --version=$GitBuildVersionSimple \
    #       --configuration=Release

    # - name: Publish tool
    #   run: |
    #     dotnet nuget push ./out/shared/DotnetTool/nupkg/Release/*.nupkg \
    #       --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
