name: "release-homebrew"
on:
  release:
    types: [released]
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    environment: release
    steps:
    - name: Update Homebrew tap
      uses: mjcheetham/update-homebrew@v1.3
      with:
        token: ${{ secrets.HOMEBREW_TOKEN }}
        tap: ldennington/homebrew-cask
        name: git-credential-manager
        type: cask
        releaseAsset: |
          gcm-osx-x64-(.*)\.pkg
          gcm-osx-arm64-(.*)\.pkg
